api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet
# from api.views import BookReviewDetailAPIView, BookReviewListAPIView

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename="reviews")

app_name = "api"
urlpatterns = router.urls

friends/urls.py
from django.urls import path
from friends.views import FriendsChatView, FriendshipRequestView, CreateFriendshipRequestView, DontFriendshipView, ConfirmDeleteFriendshipView, DeleteFriendshipView, FriendsView, DeleteMessageView

app_name = "friends"

urlpatterns = [
    path('', FriendsView.as_view(), name="friends"),
    path("requests/", FriendshipRequestView.as_view(), name="friends_requests"),
    path('create/friendship/user/<int:id>/', CreateFriendshipRequestView.as_view(), name="create_friendship"),
    path('delete/request/<int:id>/', DontFriendshipView.as_view(), name="delete_request"),
    path("confirm/delete/friend/<int:id>/", ConfirmDeleteFriendshipView.as_view(), name="conf_del_friend"),
    path('delete/friend/<int:id>/', DeleteFriendshipView.as_view(), name="delete_friend"),
    path('chat/<int:id>/', FriendsChatView.as_view(), name="friends_chat"),
    path('<int:id>/delete/message/<int:msg_id>/', DeleteMessageView.as_view(), name="delete_message"), 
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from posts.views import PostsView


urlpatterns = [
    path('', PostsView.as_view(), name="landing_page"),
    path('home/', home_page, name="home_page"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include("books.urls")),
    path('friends/', include("friends.urls")),
    path('posts/', include("posts.urls")),
    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import LikeView, DeleteLikeView, DeletePostCommentView


app_name = "posts"

urlpatterns = [
    path("like/", LikeView.as_view(), name="like"),
    path("like/delete/", DeleteLikeView.as_view(), name="delete_like"),
    path('delete/comment/', DeletePostCommentView.as_view(), name="delete_com"),
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView


app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
    path('<int:id>/profile/edit/', ProfileUpdateView.as_view(), name="profile-edit"),
]

posts/models.py
from mimetypes import guess_type
from django.db import models
from django.utils import timezone
from users.models import CustomUser


class Posts(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    file = models.FileField(upload_to='videos_uploaded',null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(CustomUser, related_name="likes", blank=True)
    
    def __str__(self):
        return self.title


class PostComments(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Пользователь {self.user} прокоментировал {self.post.title}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.jpg")

users/forms.py
from django import forms

from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from users.forms import UserCreateForm, UserUpdateForm
from users.models import CustomUser


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        return render(request, 'users/register.html', context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()  
            return redirect('users:login')
        else:
            context = {
                "form": create_form
            }
            return render(request, 'users/register.html', context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        return render(request, "users/login.html", {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, "You have successfully logged in.")
            return redirect("books:list")
        else:
            return render(request, "users/login.html", {"login_form": login_form})


class ProfileView(View):
    def get(self, request, id):
        user = CustomUser.objects.get(id=id)
        response = ''
        friends = None
        subscriptions_req = request.GET.get("user", "")
        subscribers = user.friendship_requests_to.all().count()
        subscriptions = user.friendship_requests_from.all().count()
        sub = {'subscribers': subscribers, 'subscriptions':subscriptions}
        if request.user.is_authenticated:
            for to in request.user.friendship_requests_from.all():
                if to.to_user == user:
                    response = 'request'
            for frm in request.user.friendship_requests_to.all():
                if frm.from_user == user:
                    response = 'to_request'
            for n in request.user.friends_to.all():
                if n.from_user == user:
                    response = 'friends'
                    friends = n
            for n in request.user.friends_from.all():
                if n.to_user == user:
                    response = 'friends'
                    friends = n

        return render(request, "users/profile.html", {"user": user, "response":response, "friends":friends, "sub":sub, "user_sub_req":subscriptions_req})


class LogoutView(LoginRequiredMixin,View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("landing_page")


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = CustomUser.objects.get(id=id)
        user_update_form = UserUpdateForm(instance=user)
        if request.user == user:
            return render(request, "users/profile_edit.html", {'form':user_update_form})
        return redirect(reverse("users:profile", kwargs={"id":id}))
        
    
    def post(self, request, id):
        user = CustomUser.objects.get(id=id)
        user_update_form = UserUpdateForm(
            instance=user,
            data=request.POST,
            files=request.FILES
        )
        if request.user == user:
            if user_update_form.is_valid():
                user_update_form.save()
                messages.success(request, "You have successfully updated your profile.")
                return redirect(reverse("users:profile", kwargs={"id":user.id}))
            
            return render(request, "users/profile_edit.html", {"form":user_update_form})
        
        return redirect(reverse("users:profile", kwargs={"id":id}))

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Login Page{% endblock %}
{% block content %}

<h3>Login</h3>

<div class="row">
    <div class="col-4">
        <form method="post">
            {% csrf_token %}
            {{ login_form | crispy }}
        <button class="btn btn-primary" type="submit">Log in</button><span class="ms-3">No account? Then, <a href="{% url 'users:register' %}">get registered</a></span>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% comment %} {% load dinotags %} {% endcomment %}
{% block title %}Profile Page{% endblock %}
{% block content %}

<div class="profile-containner">
    <div class="profile-image"><img class="profile-picture" src="{{ user.profile_picture.url }}" alt=""></div>
    <div class="profile-inf">
    <h3>{{ user.username }}</h3>
    <h5>{{ user.first_name }} {{ user.last_name }}</h5>
    <h6>{{ user.email }}</h6>
    </div>
    <div class="profile-users">
        <a href="{% url 'users:profile' user.id %}?user=subscribers">Подписчики: <span>{{ sub.subscribers }}</span></a>
        <a href="{% url 'users:profile' user.id %}?user=subscriptions">Подписки: <span>{{ sub.subscriptions }}</span></a>
    </div>
    <div class="profile-active">
    {% if request.user == user %}
        <a class="btn btn-dark" href="{% url 'users:profile-edit' user.id %}">Edit Profile</a>
        {% comment %} <span>Joined {{ user.date_joined | date:"M d, Y" }}</span> {% endcomment %}
    {% else %}
        {% if request.user.is_authenticated %}
            {% if response == 'friends' %}
            <div class="dropdown">
                <a href="{% url 'friends:friends_chat' friends.id %}" class="btn btn-dark">Написать</a>
                <i class="btn btn-dark dropdown-toggle bi bi-person-check" type="button" data-bs-toggle="dropdown" aria-expanded="false"></i>
                <ul class="dropdown-menu">
                  <li><form style="display: inline;" action="{% url 'friends:delete_friend' user.id %}" method="post">{% csrf_token %}<input type="hidden" name="req" value="{{ request.path }}"><button class="dropdown-item btn btn-dark" style="border: none;background: none;color: royalblue;text-decoration: underline;" type="submit">Отписаться</button></form></li>
                </ul>
              </div>
            {% elif response == 'request' %}
                <form action="{% url 'friends:delete_friend' user.id %}" method="post">{% csrf_token %}<input type="hidden" name="req" value="{{ request.path }}"><button class="btn btn-dark" type="submit">Отписаться</button></form>
            {% elif response == 'to_request' %}
                <a href="{% url 'friends:create_friendship' user.id %}" class="btn btn-dark">Подписаться в ответ</a>
            {% else %} 
                <a class="btn btn-dark" href="{% url 'friends:create_friendship' user.id %}">Подписаться</a>
            {% endif %}     
        {% endif %}
    {% endif %}
</div>

</div>

<div class="profile-posts-link">
    <a href="#"><i class="bi bi-camera-reels"></i></a>
</div>
<div class="profile-posts">
    {% for post in user.posts_set.all %}
        {% if post.file %}
        <div class="profile-post" id="profile-post-{{ post.id }}">
            <h3>{{ post.title }}</h3>
            <div class="frofile_post_file">
                <div class="profile_post_file_containner">
                    {% if post.file.url|slice:"-4:" == ".mp4" %}
                        <a href="{% url 'landing_page' %}?comments={{ post.id }}"><i class="bi bi-play-circle-fill"></i>
                            <video>
                                <source src="{{ post.file.url }}" type="video/mp4" /> 
                            </video>
                        </a>
                    {% else %}
                        <img src="{{ post.file.url }}" alt="">
                    {% endif %}
                </div>
            </div>
            <p>{{ post.text }}</p>
            <p>{{ post.created_at }}</p>
            <div class="like-com">
                {% if request.user in post.likes.all %}
                    <form method="post" action="{% url 'posts:delete_like' %}">
                        {% csrf_token %}
                        <input name="post" type="hidden" value="{{ post.id }}">
                        <input name="back_request" type="hidden" value="users:profile">
                        <input name="kwargs" type="hidden" value="{{ user.id }}">
                        <button style="border:none; background:none;padding: unset" type="submit"><i style="color:red" class="bi bi-heart-fill"></i></button>{{ p.likes.all.count }}
                    </form>
                {% else %}
                    <form method="post" action="{% url 'posts:like' %}">
                        {% csrf_token %}
                        <input name="post" type="hidden" value="{{ post.id }}">
                        <input name="back_request" type="hidden" value="users:profile">
                        <input name="kwargs" type="hidden" value="{{ user.id }}">
                        <button style="border:none; background:none;padding: unset" type="submit"><i class="bi bi-heart"></i></button>{{ p.likes.all.count }}
                        </form>
                {% endif %}
                <a href="{% url 'landing_page' %}?comments={{ post.id }}&come_back={{ request.path }}">коментарии</a>
            </div>
        </div>
    {% endif %}
    {% endfor %}
</div>

{% if user_sub_req %}
<div class="profile-black-box">
<a class="sub_exit" href="{% url 'users:profile' user.id %}"><i class="bi bi-x"></i></a>
<div class="user_subs">
    {% if user_sub_req == "subscribers" %}
        <h4>Подписчики</h4>
        {% for user_sub in user.friendship_requests_to.all %}
        <div class="subscriber">
            <a href="{% url 'users:profile' user_sub.from_user.id %}">{{ user_sub.from_user.username }}</a> {% if user == request.user %} <a href="{% url 'friends:delete_request' user_sub.from_user.id %}">Удалить</a>
            {% comment %} <a href="">{{ user_sub.from_user.id | check_podpiski }}</a> {% endcomment %}
            {% for sub_friend in request.user.friendship_requests_from.all %}
                {% if sub_friend.to_user == user_sub.from_user %}
                    <a><i class="bi bi-person-check"></i></a> <span style="display:none" id="check_podpiski_{{ user_sub.id }}">True</span>
                {% endif %}
            {% endfor %}
            <a id="pod_otvet_{{ user_sub.id }}" href="{% url 'friends:create_friendship' user_sub.from_user.id %}">Подписаться</a>
            {% endif %}
        </div>
        <hr>
        <script>
            var sub_friend = document.getElementById("check_podpiski_{{ user_sub.id }}").innerHTML
            console.log(sub_friend)
            if (sub_friend == "True"){
                friendreqnone = document.getElementById("pod_otvet_{{ user_sub.id }}")
                friendreqnone.style.display = "none"
            }
        </script>
        {% endfor %}
    {% elif user_sub_req == "subscriptions" %}
        <h4>Подписки</h4>
        {% for user_sub in user.friendship_requests_from.all %}
        <div class="subscriber">
            <a href="{% url 'users:profile' user_sub.to_user.id %}">{{ user_sub.to_user.username }}</a>{% if request.user == user %} <form style="display: inline;" action="{% url 'friends:delete_friend' user_sub.to_user.id %}" method="post">{% csrf_token %}<input type="hidden" name="req" value="{{ request.path }}?user=subscriptions"><button style="border: none;background: none;color: royalblue;text-decoration: underline;" type="submit">Отписаться</button></form>{% endif %}
            {% for sub_friend in request.user.friendship_requests_to.all %}
                {% if sub_friend.from_user == user_sub.to_user %}
                    <a><i class="bi bi-person-check"></i></a>
                {% endif %}
            {% endfor %}
        </div>
        <hr>
        {% endfor %}
    {% endif %}
</div>
</div>
{% endif %}


{% endblock %}









{% comment %} 
<div class="image d-flex flex-column justify-content-center align-items-center">
    <button class="btn btn-secondary">
        <img class="profile-picture" src="{{ user.profile_picture.url }}" alt="Profile Picture">
    </button>
    <span class="name mt-3">{{ user.first_name }} {{ user.last_name }}</span>
    <span class="idd">@{{ user.username }}</span>
    <span class="idd">{{ user.email }}</span>
    {% if request.user == user %}
        <div class=" d-flex mt-2"><a class="btn btn-dark" href="{% url 'users:profile-edit' user.id %}">Edit Profile</a></div>
        <div class=" px-2 rounded mt-4 date "><span class="join">Joined {{ user.date_joined | date:"M d, Y" }}</span></div>
    {% else %}
        {% if request.user.is_authenticated %}
            {% if response == 'friends' %}
            <br>
            <div class="dropdown">
                <a href="{% url 'friends:friends_chat' friends.id %}" class="btn btn-dark">Написать</a>
                <i class="btn btn-dark dropdown-toggle bi bi-person-check" type="button" data-bs-toggle="dropdown" aria-expanded="false"></i>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'friends:conf_del_friend' user.id %}">Удалить друга</a></li>
                </ul>
              </div>
            {% elif response == 'request' %}
                <div class="btn btn-dark d-flex mt-2">Заявка на дружбу отправлена</div>
            {% else %} 
                <div class=" d-flex mt-2"><a class="btn btn-dark" href="{% url 'friends:create_friendship' user.id %}">Добавить в друзья</a></div>
            {% endif %}     
        {% endif %}
    {% endif %}
</div> {% endcomment %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Edit Profile</h3>

<div class="row">
    <div class="col-4">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form | crispy }}

        <button class="btn btn-primary" type="submit">Save changes</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register Page{% endblock %}
{% block content %}

<h3>Register</h3>

<div class="row">
    <div class="col-4">
        <form method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            {{ form | crispy }}
        <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
</div>


{% endblock %}