api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet
# from api.views import BookReviewDetailAPIView, BookReviewListAPIView

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename="reviews")

app_name = "api"
urlpatterns = router.urls

books/urls.py
from django.urls import path
from .views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView, AuthorsView, AuthorDetailView


app_name = "books"
urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit_review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name="confirm_delete_review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name="delete_review"),
    path("authors/", AuthorsView.as_view(), name="authors"),
    path('authors/<int:id>/', AuthorDetailView.as_view(), name="author_detail")
]

friends/urls.py
from django.urls import path
from friends.views import FriendsChatView, FriendshipRequestView, CreateFriendshipRequestView, DontFriendshipView, ConfirmDeleteFriendshipView, DeleteFriendshipView, FriendsView, DeleteMessageView

app_name = "friends"

urlpatterns = [
    path('', FriendsView.as_view(), name="friends"),
    path("requests/", FriendshipRequestView.as_view(), name="friends_requests"),
    path('create/friendship/user/<int:id>/', CreateFriendshipRequestView.as_view(), name="create_friendship"),
    path('delete/request/<int:id>/', DontFriendshipView.as_view(), name="delete_request"),
    path("confirm/delete/friend/<int:id>/", ConfirmDeleteFriendshipView.as_view(), name="conf_del_friend"),
    path('delete/friend/<int:id>/', DeleteFriendshipView.as_view(), name="delete_friend"),
    path('chat/<int:id>/', FriendsChatView.as_view(), name="friends_chat"),
    path('<int:id>/delete/message/<int:msg_id>/', DeleteMessageView.as_view(), name="delete_message"), 
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from posts.views import PostsView


urlpatterns = [
    path('', PostsView.as_view(), name="landing_page"),
    path('home/', home_page, name="home_page"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include("books.urls")),
    path('friends/', include("friends.urls")),
    path('posts/', include("posts.urls")),
    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import LikeView, DeleteLikeView, DeletePostCommentView


app_name = "posts"

urlpatterns = [
    path("like/", LikeView.as_view(), name="like"),
    path("like/delete/", DeleteLikeView.as_view(), name="delete_like"),
    path('delete/comment/', DeletePostCommentView.as_view(), name="delete_com"),
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView


app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
    path('<int:id>/profile/edit/', ProfileUpdateView.as_view(), name="profile-edit"),
]

templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' request.user.id as profile_page_url %}
{% url 'users:profile-edit' request.user.id as profile_edit_page_url %}
{% url 'friends:friends_requests' as friends_requests_url %}
{% url 'friends:friends' as friends_urls %}
{% url 'books:authors' as authors_url %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Goodreads clone{% endblock %}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav id="nav">
            <div class="ch1">
                <a href="{% url 'landing_page' %}"><h2>Goodreads Clone</h2></a>
            </div>
            <div class="ch2">
                <ul>
                    <li><a class="{% if request.path == home_page_url %}activee{% endif %}" href="{{ home_page_url }}">Домой</a></li>
                    <li><a class="{% if request.path == books_page_url %}activee{% endif %}" href="{{ books_page_url }}">Книги</a></li>
                    <li><a class="{% if request.path == authors_url %}activee{% endif %}" href="{{ authors_url }}">Авторы</a></li>
                </ul>
            </div>
            <div class="ch3">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item {% if request.path == profile_page_url %}active{% endif %}" href="{% url 'users:profile' request.user.id %}">Профиль</a></li>
                            <li><a class="dropdown-item {% if request.path == friends_urls %}active{% endif %}" href="{% url 'friends:friends' %}">Друзья</a></li>
                            <li><a class="dropdown-item position-relative {% if request.path == friends_requests_url %}active{% endif %}" href="{% url 'friends:friends_requests' %}">Уведомления
                                <span id="msg" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"><span id="message_count"></span>
                                    <span class="visually-hidden">unread messages</span></span>
                                {% for obj in request.user.friendship_requests_to.all %}
                                {% if obj.view == False %}
                                    
                                    <script>
                                        var count = document.getElementById("message_count").innerHTML
                                        if (count == ""){
                                            count = 0
                                        }
                                        num = parseInt(count) + 1
                                        document.getElementById("message_count").textContent = num
                                    </script>
                                {% endif %}
                                {% endfor %}
                                <script>
                                    var count = document.getElementById("message_count").innerHTML
                                    var msg = document.getElementById("msg")
                                    if (count == ""){
                                        msg.style.display = "none"
                                    }
                                </script>
                            </a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
            <a class="btn btn-outline-light" href="{% url 'users:login' %}">Войти</a>
            {% endif %}
        </div>
        </nav>
    </header>
<main>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="mt-4">
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}

    {%  block content%}{% endblock content %}
    </div>
</main>
<div class="vverx">
    <a href="#nav">&uarr;</a>
</div>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

        {% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads clone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link 
                            {% if request.path == home_page_url %}active{% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == books_page_url %}active{% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == authors_url %}active{% endif %}" aria-current="page" href="{{ authors_url }}">Authors</a>
                        </li>
                    </ul>
                    <div class="me-4">
                        {% if request.user.is_authenticated %}
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ request.user.username }}
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end">
                                        <li><a class="dropdown-item" href="{% url 'users:profile' request.user.id %}">Профиль</a></li>
                                        <li><a class="dropdown-item" href="{% url 'friends:friends' %}">Друзья</a></li>
                                        <li><a class="dropdown-item position-relative" href="{% url 'friends:friends_requests' %}">Запросы на дружбу
                                            {% if request.user.friendship_requests_to.all.count > 0 %}
                                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                            {{ request.user.friendship_requests_to.all.count }}
                                            <span class="visually-hidden">unread messages</span></span>
                                            {% endif %}
                                        </a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                                    </ul>
                                </li>
                            </ul>
                        {% else %}
                            <a class="btn btn-outline-light" href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav> {% endcomment %}

templates/home.html
{% extends 'base.html' %}
{% block title %} Home page {% endblock %}

{% block content %}
    <h3>All reviews</h3>

    {% for review in page_obj %}
    <div class="container posts-content">
        <div class="row">
            <div class="col-lg-6">
                <div class="card mb-4">
                  <div class="card-body">
                    <div class="media mb-3">
                      <a href="{% url 'users:profile' review.user.id %}">
                        <img src="{{ review.user.profile_picture.url }}" class="d-block w-25 p-3 rounded-circle " alt="">
                      </a>
                      <div class="media-body ml-3">
                        <b>{{ review.user.username }}</b> reted this book {{ review.stars_given }} stars
                        <div class="text-muted small">{{ review.created_at | date:"M d,Y"}}</div>
                      </div>
                    </div>
                
                    <p>
                      {{ review.comment | truncatechars:300 }}
                    </p>
                    <img class="cover-pic center" src="{{ review.book.cover_picture.url }}" alt="">
                  </div>
                </div>
            </div>
        </div>
    </div> 
    {% endfor %}
    <div>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
            {% endif %}
      </ul>
    </div>
{% endblock %}

templates/landing.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="posts">    
{% for p in posts %}
    <div id="post-{{ p.id }}" class="post">
        <div class="user">
            <img class="small-profile-picture" src="{{ p.author.profile_picture.url }}" alt="">
            <a href="{% url 'users:profile' p.author.id %}"><h4>{{ p.author }}</h4></a>
        </div>
        <h4>{{ p.title }}</h4>
        {% if p.file %}
            {% if p.file.url|slice:"-4:" == ".mp4" %}
                <video class="{{ p.id }}" loop="loop" style="height:300px; width:100%" controls="controls" muted>
                    <source src="{{ p.file.url }}" type="video/mp4" /> 
                </video>
            {% else %}
                <img style="height:100%; width:100%"src="{{ p.file.url }}" alt="">
            {% endif %}
        {% endif %}
        {% if p.text %}
            <p>{{ p.text | truncatechars:250}}</p>
        {% endif %}
        <p>{{ p.created_at }}</p>
        <div class="like-com">
            {% if request.user in p.likes.all %}
                <form method="post" action="{% url 'posts:delete_like' %}">
                    {% csrf_token %}
                    <input name="post" type="hidden" value="{{ p.id }}">
                    <input name="back_request" type="hidden" value="landing_page">
                    <button style="border:none; background:none;padding: unset" type="submit"><i style="color:red" class="bi bi-heart-fill"></i></button>{{ p.likes.all.count }}
                </form>
            {% else %}
                <form method="post" action="{% url 'posts:like' %}">
                    {% csrf_token %}
                    <input name="post" type="hidden" value="{{ p.id }}">
                    <input name="back_request" type="hidden" value="landing_page">
                    <input name="" type="hidden">
                    <button style="border:none; background:none;padding: unset" type="submit"><i class="bi bi-heart"></i></button>{{ p.likes.all.count }}
                    </form>
            {% endif %}
            <a href="{% url 'landing_page' %}?comments={{ p.id }}">коментарии</a>
        </div>
    </div>
    {% if p.file.url|slice:"-4:" == ".mp4" %}
    <script>
        // Plugin isInViewport
    !function(e,n){"object"==typeof exports&&"undefined"!=typeof module?n(require("jquery"),require("window")):"function"==typeof define&&define.amd?define("isInViewport",["jquery","window"],n):n(e.$,e.window)}(this,function(e,n){"use strict";function t(n){var t=this;if(1===arguments.length&&"function"==typeof n&&(n=[n]),!(n instanceof Array))throw new SyntaxError("isInViewport: Argument(s) passed to .do/.run should be a function or an array of functions");return n.forEach(function(n){"function"!=typeof n?(console.warn("isInViewport: Argument(s) passed to .do/.run should be a function or an array of functions"),console.warn("isInViewport: Ignoring non-function values in array and moving on")):[].slice.call(t).forEach(function(t){return n.call(e(t))})}),this}function o(n){var t=e("<div></div>").css({width:"100%"});n.append(t);var o=n.width()-t.width();return t.remove(),o}function r(t,i){var a=t.getBoundingClientRect(),u=a.top,c=a.bottom,f=a.left,l=a.right,d=e.extend({tolerance:0,viewport:n},i),s=!1,p=d.viewport.jquery?d.viewport:e(d.viewport);p.length||(console.warn("isInViewport: The viewport selector you have provided matches no element on page."),console.warn("isInViewport: Defaulting to viewport as window"),p=e(n));var w=p.height(),h=p.width(),v=p[0].toString();if(p[0]!==n&&"[object Window]"!==v&&"[object DOMWindow]"!==v){var g=p[0].getBoundingClientRect();u-=g.top,c-=g.top,f-=g.left,l-=g.left,r.scrollBarWidth=r.scrollBarWidth||o(p),h-=r.scrollBarWidth}return d.tolerance=~~Math.round(parseFloat(d.tolerance)),d.tolerance<0&&(d.tolerance=w+d.tolerance),l<=0||f>=h?s:s=d.tolerance?u<=d.tolerance&&c>=d.tolerance:c>0&&u<=w}function i(n){if(n){var t=n.split(",");return 1===t.length&&isNaN(t[0])&&(t[1]=t[0],t[0]=void 0),{tolerance:t[0]?t[0].trim():void 0,viewport:t[1]?e(t[1].trim()):void 0}}return{}}e="default"in e?e.default:e,n="default"in n?n.default:n,
    e.extend(e.expr[":"],{"in-viewport":e.expr.createPseudo?e.expr.createPseudo(function(e){return function(n){return r(n,i(e))}}):function(e,n,t){return r(e,i(t[3]))}}),e.fn.isInViewport=function(e){return this.filter(function(n,t){return r(t,e)})},e.fn.run=t});
    //# isInViewport

    // Play Video
    $(function() {
    var $video = $('.{{ p.id }}');
    var $window = $(window);

    $window.scroll(function() {
    if ($video.is(":in-viewport")) {
        $video[0].play();
    } else {    
        $video[0].pause();
    }
    });
    });
    </script>
    {% endif %}
{% endfor %}
</div>
{% if com_post %}
<div class="black-window">
    {% if come_back %}
        <a class="window-link" href="{{ come_back }}#profile-post-{{com_post.id}}"><i class="bi bi-x"></i></a>
    {% else %}
        <a class="window-link" href="{% url 'landing_page' %}#post-{{com_post.id}}"><i class="bi bi-x"></i></a>
    {% endif %}
    
    <div class="post-comments"> 
        <div class="post post-detail">
            <div class="user">
                <img class="small-profile-picture" src="{{ com_post.author.profile_picture.url }}" alt="">
                <a href="{% url 'users:profile' com_post.author.id %}"><h4>{{ com_post.author }}</h4></a>
            </div>
            <h4>{{ com_post.title }}</h4>
            {% if com_post.file %}
                {% if com_post.file.url|slice:"-4:" == ".mp4" %}
                    <video class="post-detail-video" loop="loop" style="height:300px; width:100%" controls="controls" muted>
                        <source src="{{ com_post.file.url }}" type="video/mp4" /> 
                    </video>
                {% else %}
                    <img style="height:100%; width:100%"src="{{ com_post.file.url }}" alt="">
                {% endif %}
            {% endif %}
            {% if com_post.text %}
                <p class="post-detail-description">{{ com_post.text }}</p>
            {% endif %}
            <p>{{ com_post.created_at }}</p>
            <div class="like-com">
                {% if request.user in com_post.likes.all %}
                    <form method="post" action="{% url 'posts:delete_like' %}">
                        {% csrf_token %}
                        <input name="post" type="hidden" value="{{ com_post.id }}">
                        <button style="border:none; background:none;padding: unset" type="submit"><i style="color:red" class="bi bi-heart-fill"></i></button>{{ p.likes.all.count }}
                    </form>
                {% else %}
                    <form method="post" action="{% url 'posts:like' %}">
                        {% csrf_token %}
                        <input name="post" type="hidden" value="{{ com_post.id }}">
                        <button style="border:none; background:none;padding: unset" type="submit"><i class="bi bi-heart"></i></button>{{ p.likes.all.count }}
                        </form>
                {% endif %}
            </div> 
        </div>
        <div class="comments">
            <h4>Коментарии</h4>
            <div class="comments-text">
            {% for comment in comments %}
                <p><a href="{% url 'users:profile' comment.user.id %}"><b>{{ comment.user }}:</b></a> {{ comment.comment }} {% if request.user == comment.user %} <a href="{% url 'landing_page' %}?comments={{ com_post.id }}&delete_comm={{ comment.id }}"><i class="bi bi-trash"></i></a> | <a href="{% url 'landing_page' %}?comments={{ com_post.id }}&update_comm={{ comment.id }}"><i class="bi bi-pen"></i></a>{% endif %}</p>
            {% endfor %}
        </div>
            <div class="comments-form"> 
            <form method="post">
                {% csrf_token %}
                {{ form.media }}
                {{ form | crispy }}
                <button class="btn btn-success" type="submit">Отправить</button>
            </form>
        </div>
        </div>
    </div>
</div>
{% if del_com %}
    <div class="delete_post_comment">
        <h4>Вы точно хотите удалить коментарий ?</h4>
        <a class="btn btn-outline-primary" href="/?comments={{ com_post.id }}">Нет</a> | 
        <form class="delete_post_comm_form" action="{% url 'posts:delete_com' %}" method="post">{% csrf_token %}
            <input type="hidden" value="{{ del_com }}" name="com_id">
            <button class="btn btn-outline-danger" type="submit">Да</button>
        </form>
    </div>
{% endif %}
{% if com_post.file.url|slice:"-4:" == ".mp4" %}
    <script>
        // Plugin isInViewport
    !function(e,n){"object"==typeof exports&&"undefined"!=typeof module?n(require("jquery"),require("window")):"function"==typeof define&&define.amd?define("isInViewport",["jquery","window"],n):n(e.$,e.window)}(this,function(e,n){"use strict";function t(n){var t=this;if(1===arguments.length&&"function"==typeof n&&(n=[n]),!(n instanceof Array))throw new SyntaxError("isInViewport: Argument(s) passed to .do/.run should be a function or an array of functions");return n.forEach(function(n){"function"!=typeof n?(console.warn("isInViewport: Argument(s) passed to .do/.run should be a function or an array of functions"),console.warn("isInViewport: Ignoring non-function values in array and moving on")):[].slice.call(t).forEach(function(t){return n.call(e(t))})}),this}function o(n){var t=e("<div></div>").css({width:"100%"});n.append(t);var o=n.width()-t.width();return t.remove(),o}function r(t,i){var a=t.getBoundingClientRect(),u=a.top,c=a.bottom,f=a.left,l=a.right,d=e.extend({tolerance:0,viewport:n},i),s=!1,p=d.viewport.jquery?d.viewport:e(d.viewport);p.length||(console.warn("isInViewport: The viewport selector you have provided matches no element on page."),console.warn("isInViewport: Defaulting to viewport as window"),p=e(n));var w=p.height(),h=p.width(),v=p[0].toString();if(p[0]!==n&&"[object Window]"!==v&&"[object DOMWindow]"!==v){var g=p[0].getBoundingClientRect();u-=g.top,c-=g.top,f-=g.left,l-=g.left,r.scrollBarWidth=r.scrollBarWidth||o(p),h-=r.scrollBarWidth}return d.tolerance=~~Math.round(parseFloat(d.tolerance)),d.tolerance<0&&(d.tolerance=w+d.tolerance),l<=0||f>=h?s:s=d.tolerance?u<=d.tolerance&&c>=d.tolerance:c>0&&u<=w}function i(n){if(n){var t=n.split(",");return 1===t.length&&isNaN(t[0])&&(t[1]=t[0],t[0]=void 0),{tolerance:t[0]?t[0].trim():void 0,viewport:t[1]?e(t[1].trim()):void 0}}return{}}e="default"in e?e.default:e,n="default"in n?n.default:n,
    e.extend(e.expr[":"],{"in-viewport":e.expr.createPseudo?e.expr.createPseudo(function(e){return function(n){return r(n,i(e))}}):function(e,n,t){return r(e,i(t[3]))}}),e.fn.isInViewport=function(e){return this.filter(function(n,t){return r(t,e)})},e.fn.run=t});
    //# isInViewport

    // Play Video
    $(function() {
    var $video = $('.post-detail-video');
    var $window = $(window);

    $window.scroll(function() {
    if ($video.is(":in-viewport")) {
        $video[0].play();
    } else {    
        $video[0].pause();
    }
    });
    });
    </script>
    {% endif %}
{% endif %}
{% endblock %}
{% comment %} <div class="comments">
    {% if comments %}
        {% for c in comments %}
            <div class="comment ">
                <b>{{ c.user }}:</b>
                {{ c.comment }}
            </div>
        {% endfor %}
    <a href="#">Все коментарии...</a>  
    {% else %}
        коментариев не найдено
    {% endif %}
</div> {% endcomment %}

{% comment %} {% for p in posts %}
<div class="card" style="width: 25rem;">
    <h5 class="card-header">{{ p.title }}</h5>
    {% if p.file.url|slice:"-4:" == ".mp4" %}
        <video class="card-img-top" src="{{ p.file.url }}" controls></video>
    {% else %}
        <img src="{{ p.file.url }}" class="card-img-top" alt="...">
    {% endif %}
    <div class="card-body">
        <p class="card-text">{{ p.text | truncatechars:140 }}</p>
    </div>
  </div>
{% endfor %} {% endcomment %}