api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet
# from api.views import BookReviewDetailAPIView, BookReviewListAPIView

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename="reviews")

app_name = "api"
urlpatterns = router.urls

books/urls.py
from django.urls import path
from .views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView, AuthorsView, AuthorDetailView


app_name = "books"
urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit_review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name="confirm_delete_review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name="delete_review"),
    path("authors/", AuthorsView.as_view(), name="authors"),
    path('authors/<int:id>/', AuthorDetailView.as_view(), name="author_detail")
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from posts.views import PostsView


urlpatterns = [
    path('', PostsView.as_view(), name="landing_page"),
    path('home/', home_page, name="home_page"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include("books.urls")),
    path('friends/', include("friends.urls")),
    path('posts/', include("posts.urls")),
    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView


app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
    path('<int:id>/profile/edit/', ProfileUpdateView.as_view(), name="profile-edit"),
]

books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from users.models import CustomUser


class Book(models.Model):
    objects = None
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_cover.png")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()
    photo = models.ImageField(default="default_profile_pic.jpg")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} ({self.author.first_name} {self.author.last_name})"
    

class BookReview(models.Model):
    objects = None
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.stars_given} stars for "{self.book}" by {self.user.username}'

books/forms.py
from django import forms
from books.models import BookReview


class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ('stars_given', 'comment')

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from books.forms import BookReviewForm
# from django.views.generic import ListView, DetailView
from books.models import Book, BookReview, Author


# class BooksView(ListView):
#     template_name = "books/list.html"
#     queryset = Book.objects.all()
#     context_object_name = "books"
#     paginate_by = 2

class BooksView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains=search_query)
        page_size = request.GET.get("page_size", 4)
        paginator = Paginator(books, page_size)
        page_num = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_num)
        return render(request, "books/list.html", {"page_obj": page_obj, "search_query": search_query})


# class BookDetailView(DetailView):
#     template_name = "books/detail.html"
#     pk_url_kwarg = "id"
#     model = Book


class BookDetailView(View):
    def get(self, request, id):
        review_form = BookReviewForm()
        try:
            book = Book.objects.get(id=id)
        except:
            messages.warning(request, "По вашему запросу книг не найдено !")
            return redirect("books:list")
        return render(request, "books/detail.html", {"book": book, "review_form": review_form})


class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                stars_given=review_form.cleaned_data['stars_given'],
                comment=review_form.cleaned_data['comment']
            )

            return redirect(reverse("books:detail", kwargs={"id": book.id}))
        return render(request, "books/detail.html", {"book": book, "review_form": review_form})


class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)

        return render(request, "books/edit_review.html", {"book":book, "review":review, "review_form":review_form})
    
    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse("books:detail", kwargs={"id":book_id}))
        
        return render(request, "books/edit_review.html", {"book":book, "review":review, "review_form":review_form})
    

class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        return render(request, "books/confirm_delete_review.html", {"book":book, "review":review})
    

class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        review.delete()
        messages.success(request, "You have successfully deleted this review")

        return redirect(reverse("books:detail", kwargs={"id": book.id}))
    

class AuthorsView(View):
    def get(self, request):
        authors = Author.objects.all().order_by("id")
        search = request.GET.get("q", "")
        if search:
            authors = authors.filter(first_name__icontains=search)
        page_size = request.GET.get("page_size", 4)
        paginator = Paginator(authors, page_size)
        page = request.GET.get("page", "")
        page_obj = paginator.get_page(page)
        return render(request, "books/authors.html", {"page_obj":page_obj, "search_query":search})
    

class AuthorDetailView(View):
    def get(self, request, id):
        author = Author.objects.get(id=id)
        return render(request, "books/author_detail.html", {"author":author})

books/templates/books/author_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-4">
    <div class="col-2">
        <img class="author-pic" src="{{ author.photo.url }}" alt="cover image">
    </div>
    <div class="col-6 ms-3">
        <h3>{{ author.full_name }}</h3>
        <span class="fst-italic">
            {% for book_author in author.bookauthor_set.all %}
                {% if forloop.last %}
                    <a href="{% url 'books:detail' book_author.book.id %}">{{ book_author.book.title }}</a>
                {% else %}
                    <a href="{% url 'books:detail' book_author.book.id %}">{{ book_author.book.title }}</a>,
                {% endif %}
            {% endfor %}
        </span>
        <p>{{ author.bio }}</p>
    </div>
</div>  

{% endblock content %}

books/templates/books/authors.html
{% extends 'base.html' %}
{% block title %}Books Page{% endblock %}
{% block content %}

<h1>Authors</h1>

<div class="row mb-3">
    <div class="col-4">
        <form method="get" class="d-flex">
            <input type="text" class="form-control me-2" placeholder="Search" name="q" value="{{ search_query }}">
            <button type="submit" class="btn btn-success">Search</button>
        </form>
    </div>
</div>

{% if page_obj %}
    {% for author in page_obj.object_list %}
        <div class="row mb-4">
            <div class="col-2">
                <img class="author-pic" src="{{ author.photo.url }}">
            </div>
            <div class="col-6 ms-4">
                <a href="{% url 'books:author_detail' author.id %}">{{ author.full_name }}</a>
                <p>{{ author.bio | slice:":600" }}</p>
            </div>
        </div>
    {% endfor %}

    <div>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1{% if search_query %}&q={{ search_query }}{% endif %}">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if search_query%}&q={{ search_query }}{% endif %}">Previous</a></li>
            {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if search_query%}&q={{ search_query }}{% endif %}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if search_query%}&q={{ search_query }}{% endif %}">last &raquo;</a></li>
            {% endif %}
      </ul>
    </div>

{% else %}
    No authors found.
{% endif %}

{% endblock %}

books/templates/books/confirm_delete_review.html
{% extends 'base.html' %}

{% block title %} Confirm Delete Review {% endblock %}

{% block content %}
    <h3>Are you sure you want to delete this review?</h3>
    <p><b>Book: </b>{{ book.title }}</p>
    <p><b>Comment: </b>{{ review.comment }}</p>

    <a href="{% url 'books:delete_review' book.id review.id %}" class="btn btn-outline-danger">Yes</a> <a href="{% url 'books:detail' book.id %}" class="btn btn-outline-primary">No</a>
{% endblock %}

books/templates/books/detail.html
{% extends 'base.html' %}
{% block title %}Book Detail Page{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="row mb-4">
    <div class="col-2">
        <img class="cover-pic" src="{{ book.cover_picture.url }}" alt="cover image">
    </div>
    <div class="col-6 ms-3">
        <h3>{{ book.title }}</h3>
        <span class="fst-italic">
            {% for book_author in book.bookauthor_set.all %}
                {% if forloop.last %}
                    <a href="{% url 'books:author_detail' book_author.author.id %}">{{ book_author.author.full_name }}</a>
                {% else %}
                    <a href="{% url 'books:author_detail' book_author.author.id %}">{{ book_author.author.full_name }}</a>,
                {% endif %}
            {% endfor %}
        </span>
        <p>{{ book.description }}</p>
    </div>
</div>

<div class="row mb-4">
    <div class="col-6">
        <form method="post" action="{% url 'books:reviews' book.id%}">
            {% csrf_token %}
            {{ review_form | crispy }}
            <button class="btn btn-success">Add review</button>
        </form>
    </div>
</div>
{% if book.bookreview_set.exists %}
    <h4>Reviews</h4> <hr>
        {% for review in book.bookreview_set.all %}
            <div class="row mb-3">
                <div class="col-1 me-2">
                    <a href="{% url 'users:profile' review.user.id %}">
                    <img class="small-profile-picture" src="{{ review.user.profile_picture.url }}">
                    </a>
                </div>
                <div class="col-7">
                    <b>{{ review.user.username }}</b> rated it {{ review.stars_given }} stars <span class="fw-lighter">{{ review.created_at }}</span>
                    {% if review.user == request.user %}
                        <a href="{% url 'books:edit_review' book.id review.id %}"><i class="bi bi-pen"></i></a>
                        <a href="{% url 'books:confirm_delete_review' book.id review.id %}"><i class="bi bi-trash"></i></a>
                    {% endif %}
                    <p class="font-monospace mt-2">{{ review.comment }}</p>
                </div>
            </div>
        {% endfor %}
{% endif %}
{% endblock %}

books/templates/books/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Review {% endblock %}

{% block content %}
    <h3>Edit review</h3>
    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'books:edit_review' book.id review.id %}">
                {% csrf_token %}
                {{ review_form | crispy }}
                <button class="btn btn-success">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

books/templates/books/list.html
{% extends 'base.html' %}
{% block title %}Books Page{% endblock %}
{% block content %}

<h1>Books</h1>

<div class="row mb-3">
    <div class="col-4">
        <form method="get" class="d-flex">
            <input type="text" class="form-control me-2" placeholder="Search" name="q" value="{{ search_query }}">
            <button type="submit" class="btn btn-success">Search</button>
        </form>
    </div>
</div>

{% if page_obj %}
    {% for book in page_obj.object_list %}
        <div class="row mb-4">
            <div class="col-2">
                <img class="cover-pic" src="{{ book.cover_picture.url }}">
            </div>
            <div class="col-6 ms-4">
                <a href="{% url 'books:detail' book.id %}">{{ book.title }}</a>
                <p>{{ book.description | slice:":900" }}</p>
            </div>
        </div>
    {% endfor %}

    <div>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1{% if search_query%}&q={{ search_query }}{% endif %}">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if search_query%}&q={{ search_query }}{% endif %}">Previous</a></li>
            {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if search_query %}&q={{ search_query }}{% endif %}">last &raquo;</a></li>
            {% endif %}
      </ul>
    </div>

{% else %}
    No books found.
{% endif %}

{% endblock %}