api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet
# from api.views import BookReviewDetailAPIView, BookReviewListAPIView

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename="reviews")

app_name = "api"
urlpatterns = router.urls

friends/urls.py
from django.urls import path
from friends.views import FriendsChatView, FriendshipRequestView, CreateFriendshipRequestView, DontFriendshipView, ConfirmDeleteFriendshipView, DeleteFriendshipView, FriendsView, DeleteMessageView

app_name = "friends"

urlpatterns = [
    path('', FriendsView.as_view(), name="friends"),
    path("requests/", FriendshipRequestView.as_view(), name="friends_requests"),
    path('create/friendship/user/<int:id>/', CreateFriendshipRequestView.as_view(), name="create_friendship"),
    path('delete/request/<int:id>/', DontFriendshipView.as_view(), name="delete_request"),
    path("confirm/delete/friend/<int:id>/", ConfirmDeleteFriendshipView.as_view(), name="conf_del_friend"),
    path('delete/friend/<int:id>/', DeleteFriendshipView.as_view(), name="delete_friend"),
    path('chat/<int:id>/', FriendsChatView.as_view(), name="friends_chat"),
    path('<int:id>/delete/message/<int:msg_id>/', DeleteMessageView.as_view(), name="delete_message"), 
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from posts.views import PostsView


urlpatterns = [
    path('', PostsView.as_view(), name="landing_page"),
    path('home/', home_page, name="home_page"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include("books.urls")),
    path('friends/', include("friends.urls")),
    path('posts/', include("posts.urls")),
    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView


app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
    path('<int:id>/profile/edit/', ProfileUpdateView.as_view(), name="profile-edit"),
]

friends/models.py
from django.utils import timezone
from django.db import models

from users.models import CustomUser

# Create your models here.

class FriendshipRequest(models.Model):
    to_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="friendship_requests_to")
    from_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="friendship_requests_from")
    created_at = models.DateTimeField(default=timezone.now)
    view = models.BooleanField(default=False)

    def __str__(self):
        return f"ОТ {self.from_user.username} К {self.to_user.username}"
    

class Friendship(models.Model):
    to_user = models.ForeignKey(CustomUser, related_name="friends_to", on_delete=models.CASCADE)
    from_user = models.ForeignKey(CustomUser,related_name="friends_from", on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.to_user.username } И {self.from_user.username}"
    

class FriendChat(models.Model):
    friends = models.ForeignKey(Friendship, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)
    file = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"От {self.user} в чат"
    

friends/forms.py
from django import forms
from emoji_picker.widgets import EmojiPickerTextareaAdmin
from friends.models import FriendChat


class FriendChatForm(forms.ModelForm):
    text = forms.CharField(widget=EmojiPickerTextareaAdmin, required=False)

    class Meta:
        model = FriendChat
        fields = ('text', 'file')

friends/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from friends.models import FriendChat, Friendship, FriendshipRequest
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import CustomUser
from friends.forms import FriendChatForm
from django.utils import timezone


class FriendshipRequestView(LoginRequiredMixin, View):
    def get(self, request):
        for u in request.user.friendship_requests_to.all():
            if u.view == False:
                if timezone.now() >= u.created_at:
                    u.view = True
                    u.save()
        return render(request, 'friends/friendship_requests.html', {"user":request.user})

class CreateFriendshipRequestView(View):
    def get(self, request, id):
        to_user = CustomUser.objects.get(id=id)
        if request.user.is_authenticated:
            if request.user == to_user:
                messages.warning(request, "Вы не можете предложить дружбу сам себе!")
                return redirect(reverse("users:profile", kwargs={"id":to_user.id}))

            for to in request.user.friendship_requests_from.all():
                if to.to_user == to_user:
                    messages.warning(request, "Вы уже подписаны на данного пользователя !")
                    return redirect(reverse("users:profile", kwargs={"id":to_user.id}))
            else:
                FriendshipRequest.objects.create(
                    from_user = request.user,
                    to_user = to_user
                )
                for pochki in request.user.friendship_requests_to.all():
                    if pochki.from_user == to_user:
                        Friendship.objects.create(
                            from_user = to_user,
                            to_user = request.user
                        )
                        Friendship.save
                        messages.success(request, f"{to_user} теперь ваш друг !")

        return redirect(reverse("users:profile", kwargs={"id":to_user.id}))
    

class DontFriendshipView(LoginRequiredMixin ,View):
    def get(self, request, id):
        from_user = CustomUser.objects.get(id=id)
        for n in request.user.friendship_requests_to.all():
            if n.from_user == from_user:
                for f in request.user.friends_to.all():
                    if f.from_user == from_user:
                        f.delete()
                for f in request.user.friends_from.all():
                    if f.to_user == from_user:
                        f.delete()
                n.delete()
                return redirect("home_page")
            else:
                messages.warning(request, f"Пользователь {from_user.username} не отправлял вам запрос на дружбу !")
                return redirect(reverse("users:profile", kwargs={"id":from_user.id}))


class FriendsView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "friends/friends.html", {"user":request.user})
    
class ConfirmDeleteFriendshipView(View):
    def get(self, request, id):
        user = CustomUser.objects.get(id=id)

        return render(request, "friends/confirm_delete_friend.html", {"user":user})

class DeleteFriendshipView(LoginRequiredMixin, View):
    def post(self, request, id):
        try:
            user = CustomUser.objects.get(id=id)
        except:
            messages.warning(request, "Такого пользователя не существует !")
            return redirect(request.POST['req'])
        try:
            fr_req = FriendshipRequest.objects.get(from_user=request.user, to_user=user)
            fr_req.delete()
        except:
            messages.warning(request, "Подписки не найдено")
            return redirect(request.POST['req'])
        for t in request.user.friends_to.all():
            if t.from_user == user:
                t.delete()
        for t in request.user.friends_from.all():
            if t.to_user == user:
                t.delete()
        return redirect(request.POST['req'])
    

class FriendsChatView(View):
    def get(self, request, id):
        friends = Friendship.objects.get(id=id)
        if friends.to_user == request.user:
            raz = True
        elif friends.from_user == request.user:
            raz = True
        else:
            raz = False
        if raz:
            friend_chat_form = FriendChatForm()
            change = request.GET.get("change", "")
            delete = request.GET.get("delete", "")
            if change:
                try:
                    msg = FriendChat.objects.get(id=change)
                except:
                    messages.warning(request, "По вашему запросу не найдено сообщений !")
                    return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
                if msg.user == request.user:
                    friend_chat_form = FriendChatForm(instance=msg)
                else:
                    messages.warning(request, "Вам не разрешено изменить сообшения других пользователей!")
                    return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
            elif delete:
                try:
                    msg = FriendChat.objects.get(id=delete)
                except:
                    messages.warning(request, "По вашему запросу не найдено сообщений !")
                    return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
                if msg.user == request.user:
                    friend_chat_form = msg
                else:
                    messages.warning(request, "Вам не разрешено удалить сообшения других пользователей!")
                    return redirect(reverse("friends:friends_chat", kwargs={"id":id}))

            chat = friends.friendchat_set.all().order_by('created_at')
            return render(request, "friends/friend_chat.html", {"chat":chat, "friends":friends, "form": friend_chat_form})
        else:
            messages.warning(request, "Извините но вам не разрешено читать чужие сообщения !")
            return redirect("home_page")
    
    def post(self, request, id):
        friends = Friendship.objects.get(id=id)
        if friends.to_user == request.user:
            raz = True
        elif friends.from_user == request.user:
            raz = True
        else:
            raz = False
        if raz:
            friend_chat_form = FriendChatForm(data=request.POST)
            chat = friends.friendchat_set.all()
            change = request.GET.get("change", "")
        
            if request.FILES:
                file = request.FILES['file']
            else:
                file = ''
            if change:
                try:
                    msg = FriendChat.objects.get(id=change)
                except:
                    messages.warning(request, "По вашему запросу не найдено сообщений !")
                    return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
                if msg.user == request.user:
                    friend_chat_form = FriendChatForm(instance=msg, data=request.POST, files=request.FILES)
                    if friend_chat_form.is_valid():
                        if friend_chat_form.cleaned_data['text'] == '' and file=='':
                            messages.warning(request, "Вы не можете отправлять пустое значение !")
                            return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
                        else:
                            friend_chat_form.save()
                            return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
                    else:
                        return render(request, "friends/friend_chat.html", {"chat":chat, "friends":friends, "form": friend_chat_form})
                else:
                    messages.warning(request, "Вам не разрешено изменить сообшения других пользователей!")
                    return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
            elif friend_chat_form.is_valid():
                if friend_chat_form.cleaned_data['text'] == '' and file=='':
                    messages.warning(request, "Вы не можете отправлять пустое значение !")
                    return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
                else:
                    FriendChat.objects.create(
                        friends = friends,
                        user = request.user,
                        text = friend_chat_form.cleaned_data['text'],
                        file = file
                    )
                    return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
            else:
                return render(request, "friends/friend_chat.html", {"chat":chat, "friends":friends, "form": friend_chat_form})
        else:
            messages.warning(request, "Извините но вам не разрешено писать чужим пользователям !")
            return redirect("home_page")
        

class DeleteMessageView(LoginRequiredMixin,View):
    def get(self, request, msg_id, id):
        msg = FriendChat.objects.get(id=msg_id)
        if msg.user == request.user:
            msg.delete()
            return redirect(reverse("friends:friends_chat", kwargs={"id":id}))
        else:
            messages.warning(request, "Вам не разрешено удалить сообшения других пользователей!")
            return redirect(reverse("friends:friends_chat", kwargs={"id":id}))

friends/templates/friends/confirm_delete_friend.html
{% extends 'base.html' %}

{% block content %}

<h3>Вы точно хотите удалить {{ user.username }} из друзей ?</h3>

<a class="btn btn-outline-primary" href="{% url 'users:profile' user.id %}">Нет</a> | <a class="btn btn-outline-danger" href="{% url 'friends:delete_friend' user.id %}">Да</a>

{% endblock content %}

friends/templates/friends/friend_chat.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
<div class="col-5">
{% if form.id %}
<h3>вы точно хотите удалить сообщение ?</h3>
{% if form.text and form.file %}
<p>{{ form.text }}</p>
<img class="chat_img" src="{{ form.file.url }}" alt="error"><br><br>
{% elif form.text %}
<p>{{ form.text }}</p>
{% elif form.file %}
<img class="chat_img" src="{{ form.file.url }}" alt="error"><br><br>
{% endif %}
<p><a class="btn btn-primary" href="{% url 'friends:friends_chat' friends.id %}">Нет</a> | <a class="btn btn-danger" href="{% url 'friends:delete_message' friends.id form.id %}">Да</a></p>
{% else %}
<h5>Отправить сообщение</h5>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form | crispy }}
    <button class="btn btn-success" type="submit">Send</button>
</form>
{% endif %}
</div>
<div class="col-5 center">
    <h3>
        {% if friends.from_user == request.user %}
            <a href="{% url 'users:profile' friends.to_user.id %}">{{ friends.to_user.username }}</a>
        {% else %}
            <a href="{% url 'users:profile' friends.from_user.id %}">{{ friends.from_user.username }}</a>
        {% endif %}
    </h3>
    
    {% for c in chat %}
    
    <p><b>{{ c.user.username }}</b> {{ c.text }}
        {% if c.user == request.user %}
        |  <a href="{% url 'friends:friends_chat' friends.id %}?change={{ c.id }}"><i class="bi bi-pen"></i></a> | <a href="{% url 'friends:friends_chat' friends.id %}?delete={{ c.id }}"><i class="bi bi-trash"></i></a></p>
        {% endif %}
    {% if c.file %}
    <a href="{{ c.file.url }}"><img class="chat_img" src="{{ c.file.url }}" alt="error"></a>
    {% endif %}
    {% endfor %}
    </div>
</div>



{% endblock content %}

friends/templates/friends/friends.html
{% extends 'base.html' %}

{% block content %}
<h3>Друзья</h3>
{% for n in user.friends_to.all %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="people-nearby">
              <div class="nearby-user">
                <div class="row">
                  <div class="col-md-2 col-sm-2">
                    <img src="{{ n.from_user.profile_picture.url }}" alt="user" class="profile-photo-lg">
                  </div>
                  <div class="col-md-7 col-sm-7">
                    <h5><a href="{% url 'users:profile' n.from_user.id %}" class="profile-link">{{ n.from_user }}</a></h5>
                    <p>{{ n.from_user.first_name }} {{ n.from_user.last_name }}</p>
                  </div>
                  <div class="col-md-3 col-sm-3">
                    <a href="{% url 'friends:friends_chat' n.id %}" class="btn btn-primary pull-right">Написать</a>
                  </div>
                </div>
              </div>
            </div>
    	</div>
	</div>
</div>
{% endfor %}
{% for n in user.friends_from.all %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="people-nearby">
              <div class="nearby-user">
                <div class="row">
                  <div class="col-md-2 col-sm-2">
                    <img src="{{ n.to_user.profile_picture.url }}" alt="user" class="profile-photo-lg">
                  </div>
                  <div class="col-md-7 col-sm-7">
                    <h5><a href="{% url 'users:profile' n.to_user.id %}" class="profile-link">{{ n.to_user }}</a></h5>
                    <p>{{ n.to_user.first_name }} {{ n.to_user.last_name }}</p>
                  </div>
                  <div class="col-md-3 col-sm-3">
                    <a href="{% url 'friends:friends_chat' n.id %}" class="btn btn-primary pull-right">Написать</a>
                  </div>
                </div>
              </div>
            </div>
    	</div>
	</div>
</div>
{% endfor %}
{% endblock content %}

friends/templates/friends/friendship_requests.html
{% extends 'base.html' %}

{% block content %}

<h4>Уведомления</h4>
{% if user.friendship_requests_to.all %}
{% for f_request in user.friendship_requests_to.all %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="people-nearby">
              <div class="nearby-user">
                <div class="row">
                  <div class="col-md-2 col-sm-2">
                    <img src="{{ f_request.from_user.profile_picture.url }}" alt="user" class="profile-photo-lg">
                  </div>
                  <div style="width: 53.333333%" class="col-md-7 col-sm-7">
                    <h5><a href="{% url 'users:profile' f_request.from_user.id %}" class="profile-link">{{ f_request.from_user }}</a></h5>
                    <p>{{ f_request.from_user.first_name }} {{ f_request.from_user.last_name }}<br><span style="font-size:14px">Подписался(лась) на вас</span></p>
                    
                  </div>
                  <div style="width: 30%; margin:auto" class="col-md-3 col-sm-3">
                    {% for req in request.user.friendship_requests_from.all %}
                      {% if req.to_user == f_request.from_user %}
                        <form action="{% url 'friends:delete_friend' f_request.from_user.id %}" method="post">{% csrf_token %}<input type="hidden" name="req" value="{{ request.path }}"><button class="btn btn-danger pull-right no-style" type="submit">Отписаться</button></form> <span style="display:none" id="friend{{ f_request.id }}">True</span>
                      {% endif %}
                    {% endfor %}
                      
                    <div id="friend-req-none{{ f_request.id }}">
                      <a class="btn btn-danger pull-right" href="{% url 'friends:delete_request' f_request.from_user.id %}">Удалить из подписчиков</a>
                      <a class="btn btn-primary pull-right" href="{% url 'friends:create_friendship' f_request.from_user.id %}">Подписаться в ответ</a>
                  </div>
                  <script>
                    var friend = document.getElementById("friend{{ f_request.id }}").innerHTML
                    if (friend == "True") {
                      friendreqnone = document.getElementById("friend-req-none{{ f_request.id }}")
                      friendreqnone.style.display = "none"
                    }
                  </script>
                  </div>
                </div>
              </div>
            </div>
    	</div>
	</div>
</div>

{% endfor %}
{% else %}
Запросов не найдено
{% endif %}
{% endblock content %}